export const monacoLanguages = [
  { label: "Plain text", id: "text", text: "Normal text" },
  { label: "Apex", id: "apex", text: "Programming languages" },
  { label: "Azure CLI", id: "azcli", text: "Programming languages" },
  { label: "Batch", id: "bat", text: "Programming languages" },
  { label: "Cameligo", id: "cameligo", text: "Programming languages" },
  { label: "Clojure", id: "clojure", text: "Programming languages" },
  { label: "CoffeeScript", id: "coffee", text: "Programming languages" },
  { label: "C++", id: "cpp", text: "Programming languages" },
  { label: "C#", id: "csharp", text: "Programming languages" },
  { label: "CSP", id: "csp", text: "Programming languages" },
  { label: "CSS", id: "css", text: "Programming languages" },
  { label: "Dart", id: "dart", text: "Programming languages" },
  { label: "Dockerfile", id: "dockerfile", text: "Programming languages" },
  { label: "ECL", id: "ecl", text: "Programming languages" },
  { label: "Elixir", id: "elixir", text: "Programming languages" },
  { label: "F#", id: "fsharp", text: "Programming languages" },
  { label: "Go", id: "go", text: "Programming languages" },
  { label: "GraphQL", id: "graphql", text: "Programming languages" },
  { label: "Handlebars", id: "handlebars", text: "Programming languages" },
  { label: "HCL", id: "hcl", text: "Programming languages" },
  { label: "HTML", id: "html", text: "Programming languages" },
  { label: "INI", id: "ini", text: "Programming languages" },
  { label: "Java", id: "java", text: "Programming languages" },
  { label: "JavaScript", id: "javascript", text: "Programming languages" },
  { label: "JSON", id: "json", text: "Programming languages" },
  { label: "Julia", id: "julia", text: "Programming languages" },
  { label: "Kotlin", id: "kotlin", text: "Programming languages" },
  { label: "Less", id: "less", text: "Programming languages" },
  { label: "Lexon", id: "lexon", text: "Programming languages" },
  { label: "Lua", id: "lua", text: "Programming languages" },
  { label: "Markdown", id: "markdown", text: "Programming languages" },
  { label: "MIPS Assembly", id: "mips", text: "Programming languages" },
  { label: "MS-DAX", id: "msdax", text: "Programming languages" },
  { label: "MySQL", id: "mysql", text: "Programming languages" },
  { label: "Objective-C", id: "objective-c", text: "Programming languages" },
  { label: "Pascal", id: "pascal", text: "Programming languages" },
  { label: "Pascaligo", id: "pascaligo", text: "Programming languages" },
  { label: "Perl", id: "perl", text: "Programming languages" },
  { label: "Postiats", id: "postiats", text: "Programming languages" },
  { label: "Power Query", id: "powerquery", text: "Programming languages" },
  { label: "PowerShell", id: "powershell", text: "Programming languages" },
  { label: "Pug", id: "pug", text: "Programming languages" },
  { label: "Python", id: "python", text: "Programming languages" },
  { label: "R", id: "r", text: "Programming languages" },
  { label: "Razor", id: "razor", text: "Programming languages" },
  { label: "Redis", id: "redis", text: "Programming languages" },
  { label: "Redshift", id: "redshift", text: "Programming languages" },
  {
    label: "reStructuredText",
    id: "restructuredtext",
    text: "Programming languages",
  },
  { label: "Ruby", id: "ruby", text: "Programming languages" },
  { label: "Rust", id: "rust", text: "Programming languages" },
  { label: "SB", id: "sb", text: "Programming languages" },
  { label: "Scheme", id: "scheme", text: "Programming languages" },
  { label: "SCSS", id: "scss", text: "Programming languages" },
  { label: "Shell", id: "shell", text: "Programming languages" },
  { label: "Solidity", id: "solidity", text: "Programming languages" },
  { label: "Sophia", id: "sophia", text: "Programming languages" },
  { label: "SQL", id: "sql", text: "Programming languages" },
  { label: "ST", id: "st", text: "Programming languages" },
  { label: "Swift", id: "swift", text: "Programming languages" },
  { label: "Tcl", id: "tcl", text: "Programming languages" },
  { label: "Twig", id: "twig", text: "Programming languages" },
  { label: "TypeScript", id: "typescript", text: "Programming languages" },
  { label: "VB", id: "vb", text: "Programming languages" },
  { label: "Verilog", id: "verilog", text: "Programming languages" },
  { label: "XML", id: "xml", text: "Programming languages" },
  { label: "YAML", id: "yaml", text: "Programming languages" },
];
