version: "3.8"

services:
  feathercloud:
    image: onhq/feathercloud
    container_name: feathercloud
    volumes:
      - ${CONTAINER_VOLUME}:/app
    environment:
      AUTOINDEX_PATH: ${AUTOINDEX_PATH}
      WEBSERVER_PORT: ${WEBSERVER_PORT}
      ADMIN_PANEL_PORT: ${ADMIN_PANEL_PORT}
    ports:
      - ${WEBSERVER_PORT}:${WEBSERVER_PORT}
      - ${ADMIN_PANEL_PORT}:${ADMIN_PANEL_PORT}
